#spring.application.name=application


spring:
  application:
    name: application
  h2:
    console:
      enabled: true
  security:
    jwt:
      secret: ${JWT_SECRET_KEY:default_dev_key_32_chars_long_!!!}
      expiration: 86400000


  #myverysecretjwtkeythatneedstobeatleast256bits!

  datasource:
    url: jdbc:h2:mem:testdb
    #url: jbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
#      mode: always
#      schema-locations: classpath:sql/scheme.sql
#      data-locations: classpath:sql/data.sql

  thymeleaf:
    cache: false

server:
  port: 8000

logging:
  level:
    org.springframework: info
    org.mik.yftwrg: debug

